# -*- coding: utf-8 -*-
"""Generate ruler traits, capture/recruit events and their on-action hooks."""
from __future__ import annotations

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
sys.path.insert(0, str(TOOLS))
from country_cosmetics import CHARS  # noqa: E402
from ruler_data import RULERS  # noqa: E402
from focus_flavor import FOCUS_UNLOCKED_CHARACTERS, character_unlock_flag  # noqa: E402

TAGS = [
    "VCI", "SOY", "BTR", "KRZ", "KZS", "MUS", "TRF", "ZLD", "ISL", "CLB",
    "ADL", "DMK", "FDP", "CRE", "SVA", "ART", "KMS", "ZNS", "ZKR", "ZML",
    "NBL", "ISG", "HRL", "SHF",
]

IDEOLOGIES = ("democratic", "communism", "fascism", "neutrality")
IDEOLOGY_SUBTYPES = {
    "liberalism": "democratic",
    "conservatism": "democratic",
    "socialism": "democratic",
    "marxism": "communism",
    "leninism": "communism",
    "anarchist_communism": "communism",
    "fascism_ideology": "fascism",
    "falangism": "fascism",
    "despotism": "neutrality",
    "oligarchism": "neutrality",
    "centrism": "neutrality",
    "moderatism": "neutrality",
}
IDEOLOGY_MODS = {
    "democratic": {
        "stability_factor": 0.06,
        "political_power_factor": 0.05,
        "research_speed_factor": 0.03,
        "war_support_factor": -0.04,
    },
    "communism": {
        "industrial_capacity_factory": 0.08,
        "production_speed_buildings_factor": 0.05,
        "conscription_factor": 0.015,
        "consumer_goods_factor": 0.02,
    },
    "fascism": {
        "war_support_factor": 0.10,
        "army_attack_factor": 0.05,
        "army_org_factor": 0.04,
        "stability_factor": -0.04,
        "conscription_factor": 0.02,
    },
    "neutrality": {
        "political_power_factor": 0.08,
        "stability_factor": 0.03,
        "trade_opinion_factor": 0.05,
        "army_attack_factor": -0.04,
    },
}
IDEOLOGY_LABELS = {
    "democratic": "демократический курс",
    "communism": "коммунистический курс",
    "fascism": "фашистский курс",
    "neutrality": "нейтральный курс",
}


def trait_id(tag: str, ideology: str | None = None) -> str:
    suffix = f"_{ideology}" if ideology else ""
    return f"mk_ruler_{tag.lower()}{suffix}"


def map_ideology(subtype: str) -> str:
    try:
        return IDEOLOGY_SUBTYPES[subtype]
    except KeyError as exc:
        raise SystemExit(f"Unsupported leader ideology {subtype!r}; add an explicit mapping") from exc


def ruler_trait_mods(tag: str, ideology: str) -> dict[str, float]:
    mods = dict(RULERS[tag]["mods"])
    for modifier, value in IDEOLOGY_MODS[ideology].items():
        mods[modifier] = mods.get(modifier, 0) + value
    return mods


def idea_tokens(tag: str) -> tuple[str, str]:
    base = f"mk_exile_{tag.lower()}"
    return f"{base}_political", f"{base}_army"


def commander_token(tag: str) -> str:
    return f"mk_exile_general_{tag.lower()}"


SPECIAL_CHARACTER_NAMES = {
    "BTR_grandfather_akhtyamov": "Дед Ахтямов",
    "CRE_adolf_hitler_guest_instructor": "Адольф Гитлер",
    "CRE_hermann_goering_guest_instructor": "Герман Геринг",
    "CRE_erwin_rommel_guest_instructor": "Эрвин Роммель",
    "CRE_heinz_guderian_guest_instructor": "Хайнц Гудериан",
    "ZLD_grigory_yavlinsky": "Григорий Явлинский",
    "SOY_joe_biden_guest_diplomat": "Джо Байден",
}


def focus_capture_entries() -> list[tuple[str, str, str]]:
    return [
        (tag, character_id, focus_id)
        for tag in TAGS
        for character_id, focus_id in FOCUS_UNLOCKED_CHARACTERS.get(tag, {}).items()
    ]


def script_block(text: str, key: str) -> str | None:
    match = re.search(r"(?m)^\s*" + re.escape(key) + r"\s*=\s*\{", text)
    if not match:
        return None
    depth = 1
    index = match.end()
    while index < len(text) and depth:
        depth += {"{": 1, "}": -1}.get(text[index], 0)
        index += 1
    if depth:
        raise SystemExit(f"Unclosed {key} block")
    return text[match.end():index - 1]


def special_character_role(tag: str, character_id: str) -> tuple[str, str]:
    path = ROOT / "common" / "characters" / f"{tag}.txt"
    text = path.read_text(encoding="utf-8")
    character = script_block(text, character_id)
    if character is None:
        raise SystemExit(f"Missing focus-unlocked character {character_id} in {path}")
    for role in ("advisor", "corps_commander", "field_marshal"):
        body = script_block(character, role)
        if body is not None:
            return role, body
    raise SystemExit(f"Character {character_id} has no capturable role")


def capture_token(character_id: str) -> str:
    return f"mk_capture_{character_id.lower()}"


def render_traits() -> str:
    lines = [
        "# Generated by tools/build_ruler_content.py. Ruler bonuses shift with the governing ideology.",
        "leader_traits = {",
    ]
    for tag in TAGS:
        ruler = RULERS[tag]
        for ideology in (None, *IDEOLOGIES):
            current_trait = trait_id(tag, ideology)
            lines += [f"\t{current_trait} = {{", "\t\trandom = no", "\t\tsprite = 1"]
            mods = ruler["mods"] if ideology is None else ruler_trait_mods(tag, ideology)
            for modifier, value in mods.items():
                lines.append(f"\t\t{modifier} = {value:g}")
            lines += ["\t\tai_will_do = { factor = 0 }", "\t}"]
    lines.append("}")
    return "\n".join(lines) + "\n"


def attach_leader_traits(tag: str) -> None:
    path = ROOT / "common" / "characters" / f"{tag}.txt"
    lines = path.read_text(encoding="utf-8").splitlines()
    i = 0
    count = 0
    while i < len(lines):
        if lines[i].strip() != "country_leader = {":
            i += 1
            continue
        start = i
        depth = 1
        j = i + 1
        while j < len(lines) and depth:
            depth += lines[j].count("{") - lines[j].count("}")
            j += 1
        if depth:
            raise SystemExit(f"Unclosed country_leader block in {path}")
        close = j - 1
        body = lines[start + 1:close]
        ideology_line = next(
            (line.strip().split("=", 1)[1].strip() for line in body
             if line.strip().startswith("ideology =")),
            None,
        )
        if not ideology_line:
            raise SystemExit(f"Missing ideology in country_leader block in {path}")
        current_trait = trait_id(tag, map_ideology(ideology_line))
        traits_index = next(
            (start + 1 + offset for offset, line in enumerate(body)
             if line.strip().startswith("traits =")),
            None,
        )
        if traits_index is None:
            indent = lines[start][:len(lines[start]) - len(lines[start].lstrip())] + "\t"
            lines.insert(close, f"{indent}traits = {{ {current_trait} }}")
            close += 1
        else:
            traits_line = lines[traits_index]
            traits_match = re.search(r"traits\s*=\s*\{([^}]*)\}", traits_line)
            if not traits_match:
                raise SystemExit(f"Unsupported traits block in {path}: {traits_line.strip()}")
            traits = [
                token for token in traits_match.group(1).split()
                if not token.startswith("mk_ruler_")
            ]
            traits.append(current_trait)
            lines[traits_index] = re.sub(
                r"traits\s*=\s*\{[^}]*\}",
                "traits = { " + " ".join(traits) + " }",
                traits_line,
                count=1,
            )
        count += 1
        i = close + 1
    if count != 4:
        raise SystemExit(f"Expected four country_leader roles in {path}, found {count}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render_capture_actions() -> str:
    lines = [
        "\t# BEGIN generated ruler-capture actions",
        "\ton_capitulation = {",
        "\t\teffect = {",
    ]
    for index, tag in enumerate(TAGS, start=1):
        lines += [
            "\t\t\tif = {",
            "\t\t\t\tlimit = {",
            "\t\t\t\t\tROOT = {",
            f"\t\t\t\t\t\toriginal_tag = {tag}",
            "\t\t\t\t\t\tis_mk_country = yes",
            "\t\t\t\t\t\tNOT = { has_country_flag = mk_ruler_exiled }",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "\t\t\t\tROOT = {",
            "\t\t\t\t\tset_country_flag = mk_ruler_exiled",
            *[
                f"\t\t\t\t\tremove_country_leader_trait = {trait_id(tag, ideology)}"
                for ideology in IDEOLOGIES
            ],
            "\t\t\t\t}",
            "\t\t\t\tFROM = {",
            f"\t\t\t\t\tcountry_event = {{ id = mk_ruler.{index} days = 1 }}",
            "\t\t\t\t}",
            "\t\t\t}",
        ]
    for index, tag in enumerate(TAGS, start=25):
        lines += [
            "\t\t\tif = {",
            "\t\t\t\tlimit = {",
            "\t\t\t\t\tROOT = {",
            f"\t\t\t\t\t\toriginal_tag = {tag}",
            "\t\t\t\t\t\tis_mk_country = yes",
            "\t\t\t\t\t\tNOT = { has_country_flag = mk_general_exiled }",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "\t\t\t\tROOT = { set_country_flag = mk_general_exiled }",
            "\t\t\t\tFROM = {",
            f"\t\t\t\t\tcountry_event = {{ id = mk_ruler.{index} days = 1 }}",
            "\t\t\t\t}",
            "\t\t\t}",
        ]
    for event_index, (tag, character_id, _focus_id) in enumerate(focus_capture_entries(), start=49):
        captured_flag = f"mk_captured_character_{character_id.lower()}"
        lines += [
            "\t\t\tif = {",
            "\t\t\t\tlimit = {",
            "\t\t\t\t\tROOT = {",
            f"\t\t\t\t\t\toriginal_tag = {tag}",
            f"\t\t\t\t\t\thas_country_flag = {character_unlock_flag(character_id)}",
            "\t\t\t\t\t}",
            "\t\t\t\t\tFROM = { NOT = { has_country_flag = " + captured_flag + " } }",
            "\t\t\t\t}",
            "\t\t\t\tFROM = {",
            f"\t\t\t\t\tset_country_flag = {captured_flag}",
            f"\t\t\t\t\tcountry_event = {{ id = mk_ruler.{event_index} days = 1 }}",
            "\t\t\t\t}",
            "\t\t\t}",
        ]
    lines += ["\t\t}", "\t}", "", "\ton_uncapitulation = {", "\t\teffect = {"]
    for tag in TAGS:
        lines += [
            "\t\t\t\tif = {",
            "\t\t\t\t\tlimit = {",
            f"\t\t\t\t\t\toriginal_tag = {tag}",
            "\t\t\t\t\t\thas_country_flag = mk_ruler_exiled",
            "\t\t\t\t\t}",
            "\t\t\t\t\tif = {",
        ]
        for ideology in IDEOLOGIES:
            lines += [
                "\t\t\t\t\t\t" + ("if" if ideology == IDEOLOGIES[0] else "else_if") + " = {",
                f"\t\t\t\t\t\t\tlimit = {{ has_government = {ideology} }}",
                f"\t\t\t\t\t\t\tadd_country_leader_trait = {trait_id(tag, ideology)}",
                "\t\t\t\t\t\t}",
            ]
        lines += [
            "\t\t\t\t\t}",
            "\t\t\t\t\tclr_country_flag = mk_ruler_exiled",
            "\t\t\t\t}",
        ]
        lines += [
            "\t\t\t\tif = {",
            "\t\t\t\t\tlimit = {",
            f"\t\t\t\t\t\toriginal_tag = {tag}",
            "\t\t\t\t\t\thas_country_flag = mk_general_exiled",
            "\t\t\t\t\t}",
            "\t\t\t\t\tclr_country_flag = mk_general_exiled",
            "\t\t\t\t}",
        ]
    lines += ["\t\t}", "\t}", "\t# END generated ruler-capture actions"]
    return "\n".join(lines)


def patch_on_actions() -> None:
    path = ROOT / "common" / "on_actions" / "mk_on_actions.txt"
    text = path.read_text(encoding="utf-8")
    begin = "\t# BEGIN generated ruler-capture actions"
    end = "\t# END generated ruler-capture actions"
    if begin in text and end in text:
        left = text.index(begin)
        right = text.index(end, left) + len(end)
        text = text[:left] + text[right:]
    closing = text.rfind("}")
    if closing < 0:
        raise SystemExit(f"Could not find on_actions root close in {path}")
    text = text[:closing].rstrip() + "\n\n" + render_capture_actions() + "\n" + text[closing:]
    path.write_text(text, encoding="utf-8")


def render_events() -> tuple[str, str]:
    events = [
        "# Generated by tools/build_ruler_content.py — former rulers can serve as political or military advisors.",
        "add_namespace = mk_ruler",
    ]
    loc = ["l_russian:"]
    for index, tag in enumerate(TAGS, start=1):
        ruler = RULERS[tag]
        name_key = CHARS[tag]
        trait = trait_id(tag)
        political_token, army_token = idea_tokens(tag)
        base_token = f"mk_exile_{tag.lower()}"
        title = f"Судьба правителя: {ruler['title'].lower()}"
        desc = (
            f"{ruler['title']} потерял власть после падения {tag}. Победитель может использовать его опыт: "
            "назначить его политическим советником или включить в Верховное командование. "
            "Его прежние таланты остаются сильными, но вместе с ними приходят прежние слабости."
        )
        loc += [
            f' mk_ruler.{index}.t:0 "{title}"',
            f' mk_ruler.{index}.d:0 "{desc}"',
            f' mk_ruler.{index}.a:0 "Назначить политическим советником"',
            f' mk_ruler.{index}.b:0 "Назначить в Верховное командование"',
            f' {trait}:0 "{ruler["title"]}"',
            f' {trait}_desc:0 "{ruler["desc"]}"',
        ]
        for ideology in IDEOLOGIES:
            ideological_trait = trait_id(tag, ideology)
            loc += [
                f' {ideological_trait}:0 "{ruler["title"]}: {IDEOLOGY_LABELS[ideology]}"',
                f' {ideological_trait}_desc:0 "{ruler["desc"]} При выбранном курсе: {IDEOLOGY_LABELS[ideology]}."',
            ]
        events += [
            "",
            "country_event = {",
            f"\tid = mk_ruler.{index}",
            f"\ttitle = mk_ruler.{index}.t",
            f"\tdesc = mk_ruler.{index}.d",
            "\tpicture = GFX_report_event_generic_sign_treaty1",
            "\tis_triggered_only = yes",
            "\timmediate = {",
            f"\t\tif = {{ limit = {{ NOT = {{ has_country_flag = mk_has_exile_{tag.lower()} }} }}",
            f"\t\t\tset_country_flag = mk_has_exile_{tag.lower()}",
            "\t\t\tgenerate_character = {",
            f"\t\t\t\ttoken_base = {base_token}",
            f"\t\t\t\tname = {name_key}",
            "\t\t\t\tadvisor = {",
            "\t\t\t\t\tslot = political_advisor",
            "\t\t\t\t\tcost = 0",
            "\t\t\t\t\tidea_token = political",
            f"\t\t\t\t\ttraits = {{ {trait} }}",
            "\t\t\t\t\tallowed = { always = yes }",
            "\t\t\t\t}",
            "\t\t\t\tadvisor = {",
            "\t\t\t\t\tslot = high_command",
            "\t\t\t\t\tcost = 0",
            "\t\t\t\t\tidea_token = army",
            "\t\t\t\t\tledger = army",
            f"\t\t\t\t\ttraits = {{ {trait} }}",
            "\t\t\t\t\tallowed = { always = yes }",
            "\t\t\t\t}",
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.a",
            f"\t\tactivate_advisor = {political_token}",
            "\t\tadd_political_power = 25",
            "\t\tai_chance = { factor = 65 }",
            "\t}",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.b",
            f"\t\tactivate_advisor = {army_token}",
            "\t\tarmy_experience = 15",
            "\t\tai_chance = { factor = 35 }",
            "\t}",
            "}",
        ]
    for index, tag in enumerate(TAGS, start=25):
        token = commander_token(tag)
        character = f"{tag}_mk_general"
        trait = trait_id(tag)
        loc += [
            f' {character}:0 "Командующий {tag}"',
            f' mk_ruler.{index}.t:0 "Пленный штабист: {tag}"',
            f' mk_ruler.{index}.d:0 "После капитуляции {tag} один из его командиров может перейти на службу победителю. Его можно назначить командиром дивизии или военным советником."',
            f' mk_ruler.{index}.a:0 "Зачислить командиром сухопутных войск"',
            f' mk_ruler.{index}.b:0 "Назначить в Верховное командование"',
            f' mk_ruler.{index}.c:0 "Отклонить предложение"',
        ]
        events += [
            "",
            "country_event = {",
            f"\tid = mk_ruler.{index}",
            f"\ttitle = mk_ruler.{index}.t",
            f"\tdesc = mk_ruler.{index}.d",
            "\tpicture = GFX_report_event_generic_sign_treaty1",
            "\tis_triggered_only = yes",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.a",
            "\t\ttrigger = {",
            f"\t\t\tNOT = {{ has_country_flag = mk_has_{token}_commander }}",
            "\t\t}",
            "\t\tif = {",
            f"\t\t\tlimit = {{ NOT = {{ has_country_flag = mk_has_{token}_commander }} }}",
            f"\t\t\tset_country_flag = mk_has_{token}_commander",
            "\t\t\tgenerate_character = {",
            f"\t\t\t\ttoken_base = {token}",
            f"\t\t\t\tname = {character}",
            "\t\t\t}",
            "\t\t}",
            "\t\tadd_corps_commander_role = {",
            f"\t\t\tcharacter = {token}",
            "\t\t\tskill = 3",
            "\t\t\tattack_skill = 3",
            "\t\t\tdefense_skill = 2",
            "\t\t\tplanning_skill = 2",
            "\t\t\tlogistics_skill = 1",
            "\t\t}",
            "\t\tarmy_experience = 10",
            "\t\tai_chance = { factor = 65 }",
            "\t}",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.b",
            "\t\ttrigger = {",
            f"\t\t\tNOT = {{ has_country_flag = mk_has_{token}_advisor }}",
            "\t\t}",
            "\t\tif = {",
            f"\t\t\tlimit = {{ NOT = {{ has_country_flag = mk_has_{token}_advisor }} }}",
            f"\t\t\tset_country_flag = mk_has_{token}_advisor",
            "\t\t\tgenerate_character = {",
            f"\t\t\t\ttoken_base = {token}_advisor",
            f"\t\t\t\tname = {character}",
            "\t\t\t\tadvisor = {",
            "\t\t\t\t\tslot = high_command",
            "\t\t\t\t\tcost = 0",
            "\t\t\t\t\tidea_token = army",
            "\t\t\t\t\tledger = army",
            f"\t\t\t\t\ttraits = {{ {trait} }}",
            "\t\t\t\t\tallowed = { always = yes }",
            "\t\t\t\t}",
            "\t\t\t}",
            "\t\t}",
            f"\t\tactivate_advisor = {token}_advisor_army",
            "\t\tarmy_experience = 10",
            "\t\tai_chance = { factor = 30 }",
            "\t}",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.c",
            "\t\tadd_political_power = 10",
            "\t\tai_chance = { factor = 5 }",
            "\t}",
            "}",
        ]
    for index, (tag, character_id, _focus_id) in enumerate(focus_capture_entries(), start=49):
        role, role_body = special_character_role(tag, character_id)
        token = capture_token(character_id)
        recruit_flag = f"mk_recruited_character_{character_id.lower()}"
        display_name = SPECIAL_CHARACTER_NAMES.get(character_id, character_id)
        trait_match = re.search(r"\btraits\s*=\s*\{([^}]*)\}", role_body, re.S)
        traits = " ".join(trait_match.group(1).split()) if trait_match else ""
        if role == "advisor":
            slot_match = re.search(r"\bslot\s*=\s*(\w+)", role_body)
            slot = slot_match.group(1) if slot_match else ""
            if slot == "political_advisor":
                idea_token = "political"
                option_name = "Назначить политическим советником"
            elif slot == "high_command":
                idea_token = "army"
                option_name = "Включить в Верховное командование"
            else:
                raise SystemExit(f"Unsupported captured advisor slot {slot!r} for {character_id}")
            recruit_effect = [
                "\t\t\tgenerate_character = {",
                f"\t\t\t\ttoken_base = {token}",
                f"\t\t\t\tname = {character_id}",
                "\t\t\t\tadvisor = {",
                f"\t\t\t\t\tslot = {slot}",
                "\t\t\t\t\tcost = 0",
                f"\t\t\t\t\tidea_token = {idea_token}",
            ]
            if traits:
                recruit_effect.append(f"\t\t\t\t\ttraits = {{ {traits} }}")
            recruit_effect += [
                "\t\t\t\t\tallowed = { always = yes }",
                "\t\t\t\t}",
                "\t\t\t}",
                f"\t\t\tactivate_advisor = {token}_{idea_token}",
            ]
        elif role in ("corps_commander", "field_marshal"):
            option_name = "Зачислить командиром" if role == "corps_commander" else "Назначить фельдмаршалом"
            recruit_effect = [
                "\t\t\tgenerate_character = {",
                f"\t\t\t\ttoken_base = {token}",
                f"\t\t\t\tname = {character_id}",
                "\t\t\t}",
                f"\t\t\tadd_{role}_role = {{",
                f"\t\t\t\tcharacter = {token}",
            ]
            for field in ("skill", "attack_skill", "defense_skill", "planning_skill", "logistics_skill"):
                match = re.search(r"\b" + field + r"\s*=\s*([\w.]+)", role_body)
                if not match:
                    raise SystemExit(f"Missing {field} in {role} for {character_id}")
                recruit_effect.append(f"\t\t\t\t{field} = {match.group(1)}")
            if traits:
                recruit_effect.append(f"\t\t\t\ttraits = {{ {traits} }}")
            recruit_effect.append("\t\t\t}")
        else:
            raise SystemExit(f"Unsupported captured character role {role!r} for {character_id}")

        loc += [
            f' mk_ruler.{index}.t:0 "Пленный: {display_name}"',
            f' mk_ruler.{index}.d:0 "После капитуляции {tag} {display_name} может продолжить службу у победителя. Назначить его на прежнюю должность?"',
            f' mk_ruler.{index}.a:0 "{option_name}"',
            f' mk_ruler.{index}.b:0 "Отказаться от его услуг"',
        ]
        events += [
            "",
            "country_event = {",
            f"\tid = mk_ruler.{index}",
            f"\ttitle = mk_ruler.{index}.t",
            f"\tdesc = mk_ruler.{index}.d",
            "\tpicture = GFX_report_event_generic_sign_treaty1",
            "\tis_triggered_only = yes",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.a",
            "\t\tif = {",
            f"\t\t\tlimit = {{ NOT = {{ has_country_flag = {recruit_flag} }} }}",
            f"\t\t\tset_country_flag = {recruit_flag}",
            *recruit_effect,
            "\t\t}",
            "\t\tai_chance = { factor = 80 }",
            "\t}",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.b",
            "\t\tadd_political_power = 10",
            "\t\tai_chance = { factor = 20 }",
            "\t}",
            "}",
        ]
    return "\n".join(events) + "\n", "\n".join(loc) + "\n"


def main() -> None:
    if set(RULERS) != set(TAGS) or set(CHARS) < set(TAGS):
        raise SystemExit("RULERS / CHARS do not cover the 24 MK country tags")
    for tag in TAGS:
        attach_leader_traits(tag)
    (ROOT / "common" / "country_leader").mkdir(parents=True, exist_ok=True)
    (ROOT / "common" / "country_leader" / "mk_ruler_traits.txt").write_text(
        render_traits(), encoding="utf-8"
    )
    events, loc = render_events()
    (ROOT / "events" / "mk_ruler_events.txt").write_text(events, encoding="utf-8")
    (ROOT / "localisation" / "russian" / "mk_rulers_l_russian.yml").write_text(
        "\ufeff" + loc, encoding="utf-8"
    )
    patch_on_actions()
    print(f"Generated unique ruler traits and capture events for {len(TAGS)} countries")


if __name__ == "__main__":
    main()
