# -*- coding: utf-8 -*-
"""Generate ruler traits, capture/recruit events and their on-action hooks."""
from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
sys.path.insert(0, str(TOOLS))
from country_cosmetics import CHARS  # noqa: E402
from ruler_data import RULERS  # noqa: E402

TAGS = [
    "VCI", "SOY", "BTR", "KRZ", "KZS", "MUS", "TRF", "ZLD", "ISL", "CLB",
    "ADL", "DMK", "FDP", "CRE", "SVA", "ART", "KMS", "ZNS", "ZKR", "ZML",
    "NBL", "ISG", "HRL", "SHF",
]


def trait_id(tag: str) -> str:
    return f"mk_ruler_{tag.lower()}"


def idea_tokens(tag: str) -> tuple[str, str]:
    base = f"mk_exile_{tag.lower()}"
    return f"{base}_political", f"{base}_army"


def render_traits() -> str:
    lines = [
        "# Generated by tools/build_ruler_content.py. Each active ruler has a distinct strong trait with a drawback.",
        "leader_traits = {",
    ]
    for tag in TAGS:
        ruler = RULERS[tag]
        lines += [f"\t{trait_id(tag)} = {{", "\t\trandom = no", "\t\tsprite = 1"]
        for modifier, value in ruler["mods"].items():
            lines.append(f"\t\t{modifier} = {value:g}")
        lines += ["\t\tai_will_do = { factor = 0 }", "\t}"]
    lines.append("}")
    return "\n".join(lines) + "\n"


def attach_leader_traits(tag: str) -> None:
    path = ROOT / "common" / "characters" / f"{tag}.txt"
    lines = path.read_text(encoding="utf-8").splitlines()
    trait = trait_id(tag)
    i = 0
    count = 0
    while i < len(lines):
        if lines[i].strip() != "country_leader = {":
            i += 1
            continue
        start = i
        depth = 1
        j = i + 1
        while j < len(lines) and depth:
            depth += lines[j].count("{") - lines[j].count("}")
            j += 1
        if depth:
            raise SystemExit(f"Unclosed country_leader block in {path}")
        close = j - 1
        body = lines[start + 1:close]
        if not any(line.strip().startswith("traits =") for line in body):
            indent = lines[start][:len(lines[start]) - len(lines[start].lstrip())] + "\t"
            lines.insert(close, f"{indent}traits = {{ {trait} }}")
            close += 1
        elif not any(trait in line for line in body if line.strip().startswith("traits =")):
            raise SystemExit(f"Unexpected existing leader traits in {path}; update manually")
        count += 1
        i = close + 1
    if count != 4:
        raise SystemExit(f"Expected four country_leader roles in {path}, found {count}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def render_capture_actions() -> str:
    lines = [
        "\t# BEGIN generated ruler-capture actions",
        "\ton_capitulation = {",
        "\t\teffect = {",
    ]
    for index, tag in enumerate(TAGS, start=1):
        lines += [
            "\t\t\tif = {",
            "\t\t\t\tlimit = {",
            "\t\t\t\t\tROOT = {",
            f"\t\t\t\t\t\toriginal_tag = {tag}",
            "\t\t\t\t\t\tis_mk_country = yes",
            "\t\t\t\t\t\tNOT = { has_country_flag = mk_ruler_exiled }",
            "\t\t\t\t\t}",
            "\t\t\t\t}",
            "\t\t\t\tROOT = {",
            "\t\t\t\t\tset_country_flag = mk_ruler_exiled",
            f"\t\t\t\t\tremove_country_leader_trait = {trait_id(tag)}",
            "\t\t\t\t}",
            "\t\t\t\tFROM = {",
            f"\t\t\t\t\tcountry_event = {{ id = mk_ruler.{index} days = 1 }}",
            "\t\t\t\t}",
            "\t\t\t}",
        ]
    lines += ["\t\t}", "\t}", "", "\ton_uncapitulation = {", "\t\teffect = {"]
    for tag in TAGS:
        lines += [
            "\t\t\t\tif = {",
            "\t\t\t\t\tlimit = {",
            f"\t\t\t\t\t\toriginal_tag = {tag}",
            "\t\t\t\t\t\thas_country_flag = mk_ruler_exiled",
            "\t\t\t\t\t}",
            f"\t\t\t\t\tadd_country_leader_trait = {trait_id(tag)}",
            "\t\t\t\t\tclr_country_flag = mk_ruler_exiled",
            "\t\t\t\t}",
        ]
    lines += ["\t\t}", "\t}", "\t# END generated ruler-capture actions"]
    return "\n".join(lines)


def patch_on_actions() -> None:
    path = ROOT / "common" / "on_actions" / "mk_on_actions.txt"
    text = path.read_text(encoding="utf-8")
    begin = "\t# BEGIN generated ruler-capture actions"
    end = "\t# END generated ruler-capture actions"
    if begin in text and end in text:
        left = text.index(begin)
        right = text.index(end, left) + len(end)
        text = text[:left] + text[right:]
    closing = text.rfind("}")
    if closing < 0:
        raise SystemExit(f"Could not find on_actions root close in {path}")
    text = text[:closing].rstrip() + "\n\n" + render_capture_actions() + "\n" + text[closing:]
    path.write_text(text, encoding="utf-8")


def render_events() -> tuple[str, str]:
    events = [
        "# Generated by tools/build_ruler_content.py — former rulers can serve as political or military advisors.",
        "add_namespace = mk_ruler",
    ]
    loc = ["l_russian:"]
    for index, tag in enumerate(TAGS, start=1):
        ruler = RULERS[tag]
        name_key = CHARS[tag]
        trait = trait_id(tag)
        political_token, army_token = idea_tokens(tag)
        base_token = f"mk_exile_{tag.lower()}"
        title = f"Судьба правителя: {ruler['title'].lower()}"
        desc = (
            f"{ruler['title']} потерял власть после падения {tag}. Победитель может использовать его опыт: "
            "назначить его политическим советником или включить в Верховное командование. "
            "Его прежние таланты остаются сильными, но вместе с ними приходят прежние слабости."
        )
        loc += [
            f' mk_ruler.{index}.t:0 "{title}"',
            f' mk_ruler.{index}.d:0 "{desc}"',
            f' mk_ruler.{index}.a:0 "Назначить политическим советником"',
            f' mk_ruler.{index}.b:0 "Назначить в Верховное командование"',
            f' {trait}:0 "{ruler["title"]}"',
            f' {trait}_desc:0 "{ruler["desc"]}"',
        ]
        events += [
            "",
            "country_event = {",
            f"\tid = mk_ruler.{index}",
            f"\ttitle = mk_ruler.{index}.t",
            f"\tdesc = mk_ruler.{index}.d",
            "\tpicture = GFX_report_event_generic_sign_treaty1",
            "\tis_triggered_only = yes",
            "\timmediate = {",
            f"\t\tif = {{ limit = {{ NOT = {{ has_country_flag = mk_has_exile_{tag.lower()} }} }}",
            f"\t\t\tset_country_flag = mk_has_exile_{tag.lower()}",
            "\t\t\tgenerate_character = {",
            f"\t\t\t\ttoken_base = {base_token}",
            f"\t\t\t\tname = {name_key}",
            "\t\t\t\tadvisor = {",
            "\t\t\t\t\tslot = political_advisor",
            "\t\t\t\t\tcost = 0",
            "\t\t\t\t\tidea_token = political",
            f"\t\t\t\t\ttraits = {{ {trait} }}",
            "\t\t\t\t\tallowed = { always = yes }",
            "\t\t\t\t}",
            "\t\t\t\tadvisor = {",
            "\t\t\t\t\tslot = high_command",
            "\t\t\t\t\tcost = 0",
            "\t\t\t\t\tidea_token = army",
            "\t\t\t\t\tledger = army",
            f"\t\t\t\t\ttraits = {{ {trait} }}",
            "\t\t\t\t\tallowed = { always = yes }",
            "\t\t\t\t}",
            "\t\t\t}",
            "\t\t}",
            "\t}",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.a",
            f"\t\tactivate_advisor = {political_token}",
            "\t\tadd_political_power = 25",
            "\t\tai_chance = { factor = 65 }",
            "\t}",
            "\toption = {",
            f"\t\tname = mk_ruler.{index}.b",
            f"\t\tactivate_advisor = {army_token}",
            "\t\tarmy_experience = 15",
            "\t\tai_chance = { factor = 35 }",
            "\t}",
            "}",
        ]
    return "\n".join(events) + "\n", "\n".join(loc) + "\n"


def main() -> None:
    if set(RULERS) != set(TAGS) or set(CHARS) < set(TAGS):
        raise SystemExit("RULERS / CHARS do not cover the 24 MK country tags")
    for tag in TAGS:
        attach_leader_traits(tag)
    (ROOT / "common" / "country_leader").mkdir(parents=True, exist_ok=True)
    (ROOT / "common" / "country_leader" / "mk_ruler_traits.txt").write_text(
        render_traits(), encoding="utf-8"
    )
    events, loc = render_events()
    (ROOT / "events" / "mk_ruler_events.txt").write_text(events, encoding="utf-8")
    (ROOT / "localisation" / "russian" / "mk_rulers_l_russian.yml").write_text(
        "\ufeff" + loc, encoding="utf-8"
    )
    patch_on_actions()
    print(f"Generated unique ruler traits and capture events for {len(TAGS)} countries")


if __name__ == "__main__":
    main()
