# -*- coding: utf-8 -*-
"""Generate AI strategy plans, strategies, areas and theaters for Mir Kazualnosti.

Usage: python tools/build_ai.py
"""
from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / "tools"
sys.path.insert(0, str(TOOLS))
from focus_flavor import expand_spec, target_sizes  # noqa: E402

TAGS = [
    "VCI", "SOY", "BTR", "KRZ", "KZS", "MUS", "TRF", "ZLD", "ISL", "CLB",
    "ADL", "DMK", "FDP", "CRE", "SVA", "ART", "KMS", "ZNS", "ZKR", "ZML",
    "NBL", "ISG", "HRL", "SHF",
]

ALT_BRANCH = {
    "VCI": "a", "SOY": "a", "BTR": "a", "KRZ": "a", "KZS": "a", "MUS": "a",
    "TRF": "b", "ZLD": "a", "ISL": "c", "CLB": "a", "ADL": "a", "DMK": "a",
    "FDP": "b", "CRE": "a", "SVA": "b", "ART": "b", "KMS": "a", "ZNS": "b",
    "ZKR": "b", "ZML": "b", "NBL": "a", "ISG": "a", "HRL": "a", "SHF": "b",
}

AGGRESSIVE = {"BTR", "KRZ", "CRE", "DMK", "NBL", "ART", "ZNS", "VCI"}
DIPLOMATIC = {"ADL", "KMS", "HRL", "ZLD", "SOY", "SVA", "FDP", "ZKR"}
INTEGRATORS = {"DMK", "ZNS", "SHF", "HRL"}
INDUSTRIAL = {"CLB", "VCI", "SHF", "KRZ", "NBL", "CRE"}


def load_specs() -> dict:
    specs = {}
    for p in sorted(TOOLS.glob("country_data_*.py")):
        spec = importlib.util.spec_from_file_location(p.stem, p)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        for tag, raw in mod.COUNTRIES.items():
            specs[tag] = expand_spec(tag, raw)
    return specs


def section_sizes(big: bool) -> dict:
    return target_sizes(big)


def focus_ids(tag: str, sec: str, n: int) -> list[str]:
    return [f"{tag}_{sec}_{i:02d}" for i in range(n)]


def plan_focus_list(tag: str, sizes: dict, branch: str) -> str:
    parts = []
    parts += focus_ids(tag, "start", sizes["start"])
    parts += focus_ids(tag, "absurd", sizes["absurd"])
    parts += focus_ids(tag, "eco", min(3, sizes["eco"]))
    parts += focus_ids(tag, branch, sizes[branch])
    parts += focus_ids(tag, "eco", sizes["eco"])[3:]
    parts += focus_ids(tag, "army", sizes["army"])
    parts += focus_ids(tag, "diplo", sizes["diplo"])
    parts += focus_ids(tag, "secret", sizes["secret"])
    seen, ordered = set(), []
    for f in parts:
        if f not in seen:
            seen.add(f)
            ordered.append(f)
    return "\n\t\t".join(ordered)


def write_strategy_plans(specs: dict) -> None:
    out_dir = ROOT / "common/ai_strategy_plans"
    out_dir.mkdir(parents=True, exist_ok=True)
    stub = out_dir / "mk_empty.txt"
    if stub.exists():
        stub.unlink()

    chunks = ["# Generated by tools/build_ai.py — do not edit by hand\n"]
    loc_lines = ["l_russian:"]

    for tag in TAGS:
        s = specs[tag]
        sizes = section_sizes(s["big"])
        alt = ALT_BRANCH[tag]
        name = s["tree_name"]
        keep_list = plan_focus_list(tag, sizes, "keep")
        alt_list = plan_focus_list(tag, sizes, alt)
        armor = 8 if s["big"] else 2
        radical_armor = 12 if tag in AGGRESSIVE else 5

        chunks.append(f"""
{tag}_keep_plan = {{
	name = "{tag}_keep_plan"
	desc = "{tag}_keep_plan_desc"

	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		OR = {{
			is_historical_focus_on = yes
			AND = {{
				NOT = {{ has_global_flag = mk_great_political_turn }}
				check_variable = {{ global.mk_absurd_temp < 40 }}
			}}
			has_country_flag = {tag}_branch_keep
		}}
	}}
	abort = {{
		OR = {{
			has_country_flag = {tag}_branch_a
			has_country_flag = {tag}_branch_b
			has_country_flag = {tag}_branch_c
		}}
	}}

	ai_national_focuses = {{
		{keep_list}
	}}

	focus_factors = {{
		{tag}_keep_00 = 12
		{tag}_a_00 = 0.2
		{tag}_b_00 = 0.2
		{tag}_c_00 = 0.2
		{tag}_secret_00 = 0.5
		{tag}_eco_00 = 8
		{tag}_absurd_00 = 10
		{tag}_absurd_03 = 9
		{tag}_absurd_04 = 11
		{tag}_absurd_07 = 8
		{tag}_diplo_00 = 7
		{tag}_army_00 = 6
	}}

	research = {{
		industry = 25.0
		infantry_tech = 18.0
		artillery = 10.0
		support_tech = 8.0
		electronics = 6.0
	}}

	weight = {{
		factor = 1.0
	}}

	ai_strategy = {{
		type = role_ratio
		id = infantry
		value = 70
	}}
	ai_strategy = {{
		type = role_ratio
		id = armor
		value = {armor}
	}}
	ai_strategy = {{
		type = template_prio
		id = infantry
		value = 100
	}}
}}

{tag}_radical_plan = {{
	name = "{tag}_radical_plan"
	desc = "{tag}_radical_plan_desc"

	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		NOT = {{ is_historical_focus_on = yes }}
		OR = {{
			has_global_flag = mk_great_political_turn
			check_variable = {{ global.mk_absurd_temp > 39 }}
			has_country_flag = {tag}_branch_{alt}
		}}
	}}
	abort = {{
		OR = {{
			is_historical_focus_on = yes
			has_country_flag = {tag}_branch_keep
		}}
	}}

	ai_national_focuses = {{
		{alt_list}
	}}

	focus_factors = {{
		{tag}_{alt}_00 = 14
		{tag}_keep_00 = 0.3
		{tag}_secret_00 = 2.0
		{tag}_army_00 = 10
		{tag}_absurd_00 = 9
		{tag}_absurd_02 = 8
		{tag}_absurd_04 = 10
		{tag}_absurd_07 = 10
		{tag}_diplo_00 = 9
		{tag}_eco_00 = 7
	}}

	research = {{
		industry = 18.0
		infantry_tech = 28.0
		artillery = 14.0
		support_tech = 10.0
		electronics = 8.0
	}}

	weight = {{
		factor = 1.0
		modifier = {{
			factor = 2.0
			mk_absurd_high = yes
		}}
	}}

	ai_strategy = {{
		type = role_ratio
		id = infantry
		value = 65
	}}
	ai_strategy = {{
		type = role_ratio
		id = armor
		value = {radical_armor}
	}}
	ai_strategy = {{
		type = template_prio
		id = infantry
		value = 100
	}}
}}
""")
        loc_lines += [
            f' {tag}_keep_plan:0 "Курс {name}: сохранение"',
            f' {tag}_keep_plan_desc:0 "ИИ {name} сохраняет стартовую идеологию и развивает экономику."',
            f' {tag}_radical_plan:0 "Курс {name}: радикальный"',
            f' {tag}_radical_plan_desc:0 "После Великого Поворота ИИ {name} уходит в альтернативную ветку."',
        ]

    (out_dir / "mk_strategy_plans.txt").write_text("".join(chunks), encoding="utf-8")
    (ROOT / "localisation/russian/mk_ai_l_russian.yml").write_text(
        "\ufeff" + "\n".join(loc_lines) + "\n", encoding="utf-8"
    )
    print(f"strategy plans: {len(TAGS) * 2}")


def write_strategies(specs: dict) -> None:
    out_dir = ROOT / "common/ai_strategy"
    out_dir.mkdir(parents=True, exist_ok=True)
    stub = out_dir / "mk_empty.txt"
    if stub.exists():
        stub.unlink()

    lines = ["# Generated by tools/build_ai.py\n"]
    lines.append("""
mk_unit_production = {
	enable = {
		is_mk_country = yes
	}
	abort = {
		always = no
	}

	ai_strategy = {
		type = role_ratio
		id = infantry
		value = 70
	}
	ai_strategy = {
		type = role_ratio
		id = garrison
		value = 5
	}
	ai_strategy = {
		type = role_ratio
		id = armor
		value = 5
	}
	ai_strategy = {
		type = role_ratio
		id = cavalry
		value = -100
	}
	ai_strategy = {
		type = template_prio
		id = infantry
		value = 100
	}
	ai_strategy = {
		type = equipment_production_factor
		id = infantry
		value = 40
	}
	ai_strategy = {
		type = equipment_production_factor
		id = artillery
		value = 20
	}
	ai_strategy = {
		type = build_building
		id = industrial_complex
		value = 40
	}
	ai_strategy = {
		type = build_building
		id = arms_factory
		value = 30
	}
	ai_strategy = {
		type = build_building
		id = infrastructure
		value = 25
	}
	ai_strategy = {
		type = save_equipment
		id = infantry_equipment
		value = 20
	}
}

mk_alliance_drive = {
	enable = {
		is_mk_country = yes
		is_in_faction = no
		is_subject = no
		has_war = no
		has_global_flag = mk_great_political_turn
	}
	abort_when_not_enabled = yes

	ai_strategy = {
		type = pp_spend_priority
		id = relation
		value = 70
	}
	ai_strategy = {
		type = alliance
		id = SOY
		value = 30
	}
}

mk_war_focus = {
	enable = {
		is_mk_country = yes
		has_war = yes
	}
	abort_when_not_enabled = yes

	ai_strategy = {
		type = role_ratio
		id = infantry
		value = 20
	}
	ai_strategy = {
		type = force_build_armies
		value = 80
	}
	ai_strategy = {
		type = build_building
		id = arms_factory
		value = 60
	}
	ai_strategy = {
		type = equipment_production_factor
		id = infantry
		value = 50
	}
}

mk_pp_priorities = {
	enable = {
		is_mk_country = yes
	}
	abort = {
		always = no
	}
	ai_strategy = {
		type = pp_spend_priority
		id = admiral
		value = -50
	}
	ai_strategy = {
		type = pp_spend_priority
		id = guarantee
		value = -30
	}
	ai_strategy = {
		type = pp_spend_priority
		id = relation
		value = 20
	}
}

mk_absurd_aggression = {
	enable = {
		is_mk_country = yes
		mk_absurd_high = yes
	}
	abort_when_not_enabled = yes

	ai_strategy = {
		type = role_ratio
		id = infantry
		value = 10
	}
	ai_strategy = {
		type = role_ratio
		id = armor
		value = 8
	}
	ai_strategy = {
		type = force_build_armies
		value = 50
	}
	ai_strategy = {
		type = build_building
		id = arms_factory
		value = 40
	}
}
""")

    by_ideo: dict[str, list[str]] = {
        "democratic": [], "communism": [], "fascism": [], "neutrality": [],
    }
    for tag in TAGS:
        by_ideo[specs[tag]["start_ideology"]].append(tag)

    for tag in TAGS:
        ideo = specs[tag]["start_ideology"]
        friends = [t for t in by_ideo[ideo] if t != tag]
        rivals = [t for t in TAGS if t != tag and specs[t]["start_ideology"] != ideo]
        conquer_targets = rivals[:4] if tag in AGGRESSIVE else rivals[:2]

        friend_bits = []
        for f in friends:
            ally_val = 120 if tag in DIPLOMATIC else 90
            friend_bits.append(f"""
	ai_strategy = {{
		type = befriend
		id = {f}
		value = 100
	}}
	ai_strategy = {{
		type = alliance
		id = {f}
		value = {ally_val}
	}}
	ai_strategy = {{
		type = support
		id = {f}
		value = 50
	}}""")

        rival_bits = []
        for r in conquer_targets:
            val = 120 if tag in AGGRESSIVE else 40
            rival_bits.append(f"""
	ai_strategy = {{
		type = antagonize
		id = {r}
		value = {val}
	}}""")
            if tag in AGGRESSIVE:
                rival_bits.append(f"""
	ai_strategy = {{
		type = conquer
		id = {r}
		value = 50
	}}""")

        lines.append(f"""
{tag}_diplomacy_default = {{
	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		always = yes
	}}
	abort = {{
		always = no
	}}
{"".join(friend_bits)}
}}

{tag}_diplomacy_absurd = {{
	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		OR = {{
			mk_absurd_high = yes
			has_idea = mk_idea_revisionist
			has_global_flag = mk_era_crises_fired
		}}
	}}
	abort_when_not_enabled = yes
{"".join(rival_bits)}
}}
""")

        for other in TAGS:
            if other == tag:
                continue
            lines.append(f"""
{tag}_hunt_{other} = {{
	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		is_in_faction = yes
		{other} = {{
			has_idea = mk_idea_revisionist
		}}
	}}
	abort_when_not_enabled = yes

	ai_strategy = {{
		type = antagonize
		id = {other}
		value = 300
	}}
	ai_strategy = {{
		type = conquer
		id = {other}
		value = 150
	}}
	ai_strategy = {{
		type = contain
		id = {other}
		value = 100
	}}
}}
""")

        if tag in DIPLOMATIC:
            lines.append(f"""
{tag}_diplomatic_bias = {{
	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		always = yes
	}}
	abort = {{
		always = no
	}}
	ai_strategy = {{
		type = pp_spend_priority
		id = relation
		value = 80
	}}
}}
""")

        if tag in INDUSTRIAL:
            lines.append(f"""
{tag}_industrial_bias = {{
	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		always = yes
	}}
	abort = {{
		always = no
	}}
	ai_strategy = {{
		type = build_building
		id = industrial_complex
		value = 55
	}}
	ai_strategy = {{
		type = build_building
		id = infrastructure
		value = 35
	}}
}}
""")

        if tag in INTEGRATORS:
            for other in TAGS:
                if other == tag:
                    continue
                lines.append(f"""
{tag}_integrate_pressure_{other} = {{
	allowed = {{
		original_tag = {tag}
	}}
	enable = {{
		has_global_flag = mk_era_blocs_fired
		check_variable = {{ mk_mech > 49 }}
		{other} = {{
			is_neighbor_of = ROOT
			has_war = no
		}}
	}}
	abort_when_not_enabled = yes

	ai_strategy = {{
		type = befriend
		id = {other}
		value = 40
	}}
	ai_strategy = {{
		type = antagonize
		id = {other}
		value = 30
	}}
}}
""")

    path = out_dir / "mk_strategies.txt"
    path.write_text("".join(lines), encoding="utf-8")
    print(f"strategies: {path.stat().st_size} bytes")


def write_areas() -> None:
    out_dir = ROOT / "common/ai_areas"
    out_dir.mkdir(parents=True, exist_ok=True)
    stub = out_dir / "mk_empty.txt"
    if stub.exists():
        stub.unlink()
    text = """# Generated by tools/build_ai.py
areas = {

	mk_all_land = {
		strategic_regions = {
			1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
		}
	}

	mk_core_west = {
		strategic_regions = {
			1 2 3 4 5 6
		}
	}

	mk_core_center = {
		strategic_regions = {
			7 8 9 10 11 12
		}
	}

	mk_core_east = {
		strategic_regions = {
			13 14 15 16 17 18
		}
	}

	mk_core_south = {
		strategic_regions = {
			19 20 21 22 23 24
		}
	}

	mk_seas = {
		strategic_regions = {
			25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
		}
	}
}
"""
    (out_dir / "mk_areas.txt").write_text(text, encoding="utf-8")
    print("areas ok")


def write_theaters() -> None:
    out_dir = ROOT / "common/ai_faction_theaters"
    out_dir.mkdir(parents=True, exist_ok=True)
    stub = out_dir / "mk_empty.txt"
    if stub.exists():
        stub.unlink()
    text = """# Generated by tools/build_ai.py

mk_theater_kazualia = {
	name = theater_mk_kazualia
	regions = {
		1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
	}
	cancel = {
		has_war = no
	}
	ai_will_do = {
		base = 1
		modifier = {
			add = 20
			has_war = yes
			is_mk_country = yes
		}
		modifier = {
			factor = 0
			has_war = no
		}
	}
}

mk_theater_seas = {
	name = theater_mk_seas
	regions = {
		25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
	}
	cancel = {
		has_war = no
	}
	ai_will_do = {
		base = 0
		modifier = {
			add = 5
			has_war = yes
		}
	}
}
"""
    (out_dir / "mk_theaters.txt").write_text(text, encoding="utf-8")
    # theater names for loc
    loc = ROOT / "localisation/russian/mk_ai_l_russian.yml"
    body = loc.read_text(encoding="utf-8-sig")
    if "theater_mk_kazualia" not in body:
        body = body.rstrip() + (
            '\n theater_mk_kazualia:0 "Театр Казуалии"\n'
            ' theater_mk_seas:0 "Морской театр Казуалии"\n'
        )
        loc.write_text("\ufeff" + body, encoding="utf-8")
    print("theaters ok")


def patch_decision_ai() -> None:
    path = ROOT / "common/decisions/mk_global_decisions.txt"
    text = path.read_text(encoding="utf-8")
    additions = {
        "mk_dec_form_ideology_faction": """
		ai_will_do = {
			factor = 10
			modifier = {
				factor = 2
				mk_era_blocs = yes
			}
			modifier = {
				factor = 0.2
				is_historical_focus_on = yes
			}
		}""",
        "mk_dec_form_npt_protocol": """
		ai_will_do = {
			factor = 5
			modifier = {
				factor = 3
				check_variable = { mk_npt > 6 }
			}
		}""",
        "mk_dec_accuse_revisionism": """
		ai_will_do = {
			factor = 0
			modifier = {
				add = 5
				mk_absurd_high = yes
				has_war_support > 0.5
			}
			modifier = {
				factor = 0
				is_historical_focus_on = yes
			}
		}""",
        "mk_dec_condemn_revisionism": """
		ai_will_do = {
			factor = 20
		}""",
        "mk_dec_call_congress": """
		ai_will_do = {
			factor = 3
			modifier = {
				factor = 2
				check_variable = { mk_world_votes > 4 }
			}
		}""",
        "mk_dec_lobby_votes": """
		ai_will_do = {
			factor = 5
		}""",
        "mk_dec_fund_npt": """
		ai_will_do = {
			factor = 2
			modifier = {
				factor = 4
				OR = {
					original_tag = SOY
					original_tag = BTR
				}
			}
		}""",
        "mk_dec_stir_absurd": """
		ai_will_do = {
			factor = 1
			modifier = {
				factor = 3
				has_idea = mk_idea_turn_chaos
			}
			modifier = {
				factor = 0
				is_historical_focus_on = yes
			}
		}""",
        "mk_dec_calm_absurd": """
		ai_will_do = {
			factor = 2
			modifier = {
				factor = 3
				OR = {
					original_tag = ADL
					original_tag = KMS
					original_tag = ZLD
				}
			}
		}""",
        "mk_dec_goodwill_mission": """
		ai_will_do = {
			factor = 4
			modifier = {
				factor = 2
				OR = {
					original_tag = ADL
					original_tag = KMS
					original_tag = HRL
				}
			}
		}""",
        "mk_dec_prepare_war": """
		ai_will_do = {
			factor = 3
			modifier = {
				factor = 3
				mk_absurd_high = yes
			}
		}""",
        "mk_dec_invite_same_ideology": """
		ai_will_do = {
			factor = 15
		}""",
        "mk_dec_win_diplomatic": """
		ai_will_do = { factor = 100 }""",
        "mk_dec_win_ideological": """
		ai_will_do = { factor = 100 }""",
        "mk_dec_win_economic": """
		ai_will_do = { factor = 100 }""",
        "mk_dec_win_npt": """
		ai_will_do = { factor = 100 }""",
        "mk_dec_win_absurd": """
		ai_will_do = { factor = 80 }""",
        "mk_dec_win_integration": """
		ai_will_do = { factor = 100 }""",
        "mk_dec_emergency_congress": """
		ai_will_do = {
			factor = 8
			modifier = {
				factor = 2
				mk_absurd_critical = yes
			}
		}""",
        "mk_dec_mediate_neighbors": """
		ai_will_do = {
			factor = 6
		}""",
        "mk_dec_purge_revisionist": """
		ai_will_do = {
			factor = 12
		}""",
    }

    for dec_id, ai_block in additions.items():
        marker = f"\t{dec_id} = {{"
        if marker not in text:
            continue
        start = text.find(marker)
        end = text.find("\n\t}\n", start)
        if end == -1:
            continue
        region = text[start:end]
        if "ai_will_do" in region:
            continue
        text = text[:end] + "\n" + ai_block + text[end:]

    path.write_text(text, encoding="utf-8")
    print("decision AI weights patched")


def main() -> None:
    specs = load_specs()
    missing = [t for t in TAGS if t not in specs]
    if missing:
        raise SystemExit(f"missing specs: {missing}")
    write_strategy_plans(specs)
    write_strategies(specs)
    write_areas()
    write_theaters()
    patch_decision_ai()
    print("done")


if __name__ == "__main__":
    main()
