# -*- coding: utf-8 -*-
"""Unique country-leader traits for the 24 rulers of Mir Kazualnosti."""

RULERS = {
    "VCI": {
        "title": "Император случайного масштаба",
        "desc": "Сабиров раздаёт указы, заводы и политическое влияние одним росчерком. Обратная сторона трона — растущие расходы и медленно тающая стабильность.",
        "mods": {
            "political_power_factor": 0.30,
            "stability_factor": 0.20,
            "industrial_capacity_factory": 0.20,
            "army_attack_factor": 0.15,
            "consumer_goods_factor": 0.05,
            "stability_weekly": -0.0015,
        },
    },
    "SOY": {
        "title": "Главный разработчик Республики",
        "desc": "Ефимов ускоряет науку и промышленность так, будто весь мир — его стартап. Код работает быстрее, чем общество успевает полюбить войну.",
        "mods": {
            "research_speed_factor": 0.40,
            "production_speed_buildings_factor": 0.25,
            "industrial_capacity_factory": 0.15,
            "political_power_factor": 0.10,
            "war_support_factor": -0.12,
            "army_org_factor": -0.05,
        },
    },
    "BTR": {
        "title": "Чёрный маршал двух властей",
        "desc": "Ахтямов превращает сомнение в мобилизацию: армия бьёт сильнее и получает больше людей, зато наука и гражданская стабильность страдают.",
        "mods": {
            "army_attack_factor": 0.35,
            "army_org_factor": 0.25,
            "war_support_factor": 0.20,
            "conscription_factor": 0.08,
            "stability_factor": -0.12,
            "research_speed_factor": -0.08,
        },
    },
    "KRZ": {
        "title": "Архитектор железной пятилетки",
        "desc": "Пименов разгоняет заводы, штаб и политический аппарат. Пятилетка требует дорогих обещаний и постепенно выматывает население.",
        "mods": {
            "industrial_capacity_factory": 0.30,
            "production_speed_buildings_factor": 0.20,
            "army_org_factor": 0.20,
            "political_power_factor": 0.15,
            "consumer_goods_factor": 0.08,
            "stability_weekly": -0.001,
        },
    },
    "KZS": {
        "title": "Атаман Круга и неприступных рубежей",
        "desc": "Юзеева превращает станицы в крепость и быстро пополняет ряды. За оборонный характер приходится платить медленной индустрией и бюрократией.",
        "mods": {
            "army_defence_factor": 0.40,
            "conscription_factor": 0.08,
            "army_attack_factor": 0.15,
            "war_support_factor": 0.15,
            "industrial_capacity_factory": -0.10,
            "political_power_factor": -0.05,
        },
    },
    "MUS": {
        "title": "Королева двух палат",
        "desc": "Мусина удерживает страну стабильной, усиливает кабинет и виртуозно договаривается с соседями. Парламенту не нравится воинственный тон Короны.",
        "mods": {
            "stability_factor": 0.35,
            "political_power_factor": 0.25,
            "research_speed_factor": 0.15,
            "improve_relations_maintain_cost_factor": -0.30,
            "war_support_factor": -0.10,
            "army_attack_factor": -0.06,
        },
    },
    "TRF": {
        "title": "Зелёный комиссар коммун",
        "desc": "Чазов превращает кооперацию и местные ресурсы в сильную экономику. Коммунальный пацифизм делает наступательные планы менее убедительными.",
        "mods": {
            "stability_factor": 0.25,
            "local_resources_factor": 0.20,
            "production_speed_buildings_factor": 0.25,
            "conscription_factor": 0.04,
            "army_attack_factor": -0.10,
            "industrial_capacity_factory": -0.05,
        },
    },
    "ZLD": {
        "title": "Премьер вечной коалиции",
        "desc": "Сабирова собирает устойчивые коалиции, прибавляя политическую силу и заводы. Любой крупный спор требует ещё одного компромисса и бюджета.",
        "mods": {
            "political_power_factor": 0.30,
            "stability_factor": 0.30,
            "industrial_capacity_factory": 0.18,
            "trade_opinion_factor": 0.20,
            "war_support_factor": -0.08,
            "consumer_goods_factor": 0.04,
        },
    },
    "ISL": {
        "title": "Архитектор золотого века",
        "desc": "Габдрахманов ускоряет модернизацию, исследования и строительство. Консервативная осторожность слегка снижает готовность к войне и увеличивает расходы.",
        "mods": {
            "research_speed_factor": 0.28,
            "stability_factor": 0.20,
            "production_speed_buildings_factor": 0.18,
            "political_power_factor": 0.10,
            "war_support_factor": -0.08,
            "consumer_goods_factor": 0.05,
        },
    },
    "CLB": {
        "title": "Директор челябинского реактора",
        "desc": "Иванов даёт науке и промышленности реакторный разгон. Проверки безопасности, дорогие эксперименты и нервозность общества идут в комплекте.",
        "mods": {
            "research_speed_factor": 0.45,
            "production_speed_buildings_factor": 0.28,
            "industrial_capacity_factory": 0.22,
            "political_power_factor": 0.12,
            "stability_factor": -0.12,
            "consumer_goods_factor": 0.08,
        },
    },
    "ADL": {
        "title": "Арбитр всех спорных границ",
        "desc": "Айдов почти бесплатно улучшает отношения и получает огромный дипломатический вес. Его осторожность мешает поддерживать военный азарт.",
        "mods": {
            "trade_opinion_factor": 0.40,
            "improve_relations_maintain_cost_factor": -0.40,
            "political_power_factor": 0.22,
            "stability_factor": 0.15,
            "army_attack_factor": -0.12,
            "war_support_factor": -0.08,
        },
    },
    "DMK": {
        "title": "Князь генерального наступления",
        "desc": "Сидоров совмещает княжескую власть с мощным штабом и мобилизацией. Дипломатический этикет страдает, а стабильность зависит от успеха кампаний.",
        "mods": {
            "army_attack_factor": 0.30,
            "army_org_factor": 0.20,
            "political_power_factor": 0.20,
            "conscription_factor": 0.05,
            "stability_factor": -0.08,
            "trade_opinion_factor": -0.10,
        },
    },
    "FDP": {
        "title": "Председатель экзаменационной Палаты",
        "desc": "Багаутдинов производит политические очки почти промышленным способом и удерживает аппарат в порядке. Длинные заседания не помогают армии сохранять пыл.",
        "mods": {
            "political_power_factor": 0.40,
            "stability_factor": 0.20,
            "research_speed_factor": 0.16,
            "trade_opinion_factor": 0.15,
            "war_support_factor": -0.12,
            "army_attack_factor": -0.05,
        },
    },
    "CRE": {
        "title": "Начальник штаба тотального реванша",
        "desc": "Хасанов резко усиливает наступление, организацию и мобилизацию. Экономика и внутреннее спокойствие становятся заложниками реванша.",
        "mods": {
            "army_attack_factor": 0.40,
            "army_org_factor": 0.25,
            "war_support_factor": 0.25,
            "conscription_factor": 0.08,
            "industrial_capacity_factory": -0.15,
            "stability_factor": -0.12,
        },
    },
    "SVA": {
        "title": "Северный академик-мобилизатор",
        "desc": "Арифуллин разгоняет научные советы и инженерное строительство. Учёные спорят о политике, а резервов для массовой мобилизации меньше.",
        "mods": {
            "research_speed_factor": 0.40,
            "production_speed_buildings_factor": 0.20,
            "stability_factor": 0.15,
            "industrial_capacity_factory": 0.12,
            "political_power_factor": -0.10,
            "conscription_factor": -0.03,
        },
    },
    "ART": {
        "title": "Первый гражданин Айратии",
        "desc": "Гильмиев укрепляет гражданское единство, политическую власть и людской резерв. Идентичность важнее производственных показателей.",
        "mods": {
            "stability_factor": 0.30,
            "political_power_factor": 0.22,
            "conscription_factor": 0.05,
            "local_resources_factor": 0.15,
            "industrial_capacity_factory": -0.10,
            "research_speed_factor": -0.05,
        },
    },
    "KMS": {
        "title": "Мастер сети взаимных услуг",
        "desc": "Гилязов укрепляет торговлю, отношения и индустрию через партнёрства. Слишком дипломатичный курс снижает желание воевать.",
        "mods": {
            "trade_opinion_factor": 0.30,
            "improve_relations_maintain_cost_factor": -0.30,
            "industrial_capacity_factory": 0.22,
            "political_power_factor": 0.15,
            "war_support_factor": -0.10,
            "army_attack_factor": -0.05,
        },
    },
    "ZNS": {
        "title": "Союзный маршал земель",
        "desc": "Зайнутдинов делает федерацию крепкой, производительной и готовой к обороне. Централизованный союз медленно принимает решения и атакует.",
        "mods": {
            "army_defence_factor": 0.28,
            "industrial_capacity_factory": 0.25,
            "stability_factor": 0.18,
            "conscription_factor": 0.05,
            "political_power_factor": -0.08,
            "army_attack_factor": -0.05,
        },
    },
    "ZKR": {
        "title": "Генеральный подрядчик республики",
        "desc": "Закиров запускает фабрики, контракты и политические сделки. В мелком шрифте договора спрятаны расходы и недовольство.",
        "mods": {
            "industrial_capacity_factory": 0.35,
            "production_speed_buildings_factor": 0.20,
            "political_power_factor": 0.20,
            "local_resources_factor": 0.15,
            "stability_factor": -0.10,
            "consumer_goods_factor": 0.06,
        },
    },
    "ZML": {
        "title": "Председатель всеобщего схода",
        "desc": "Замалиев мобилизует общины, повышает стабильность и использует местные ресурсы. Научное развитие и крупная промышленность буксуют.",
        "mods": {
            "stability_factor": 0.30,
            "conscription_factor": 0.10,
            "political_power_factor": 0.18,
            "local_resources_factor": 0.20,
            "research_speed_factor": -0.12,
            "industrial_capacity_factory": -0.05,
        },
    },
    "NBL": {
        "title": "Президент указа и вечного плана",
        "desc": "Исханов ускоряет стройки, фабрики и исследования одним указом. Отчётность, цена проектов и недовольство растут вместе с темпом.",
        "mods": {
            "production_speed_buildings_factor": 0.35,
            "industrial_capacity_factory": 0.25,
            "political_power_factor": 0.20,
            "research_speed_factor": 0.15,
            "stability_factor": -0.10,
            "consumer_goods_factor": 0.08,
        },
    },
    "ISG": {
        "title": "Двигатель кооперативной сети",
        "desc": "Исмагилов делает кооперативы устойчивыми и производительными, набирает людей для обороны. Согласование решений съедает политическую скорость.",
        "mods": {
            "stability_factor": 0.28,
            "industrial_capacity_factory": 0.22,
            "production_speed_buildings_factor": 0.18,
            "conscription_factor": 0.05,
            "political_power_factor": -0.10,
            "trade_opinion_factor": -0.05,
        },
    },
    "HRL": {
        "title": "Купеческий арбитр Лиги",
        "desc": "Харитонов объединяет торговлю, влияние и стабильность. Купеческая осторожность оставляет армии меньше наступательного запала.",
        "mods": {
            "trade_opinion_factor": 0.30,
            "political_power_factor": 0.28,
            "industrial_capacity_factory": 0.15,
            "stability_factor": 0.12,
            "army_attack_factor": -0.10,
            "war_support_factor": -0.08,
        },
    },
    "SHF": {
        "title": "Федералист трёх печатей",
        "desc": "Шарафутдинов укрепляет оборону и производство всей Федерации. Многоуровневое согласование замедляет политические решения и наступление.",
        "mods": {
            "army_defence_factor": 0.35,
            "industrial_capacity_factory": 0.20,
            "production_speed_buildings_factor": 0.15,
            "stability_factor": 0.15,
            "political_power_factor": -0.12,
            "army_attack_factor": -0.08,
        },
    },
}
